version: '3'
services:
  my_service:
    image: lscr.io/linuxserver/blender:latest
    container_name: dvlend
    network_mode: my_custom_network
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.18.0.0/16
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
    ports:
      - 3000:3000
    volumes:
      - /path/on/your/host/machine:/config
    restart: unless-stopped
