name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kushal123123/backend-cloud-test
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: push_to_registry
    env:
      MONOGO_URI: ${{ secrets.MONOGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      LOCAL_MACHINE: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Deploy to Local Machine
        run: |
            echo "${SSH_PRIVATE_KEY}" > key.pem
            chmod 600 key.pem
            
            ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              ${SSH_USER}@${LOCAL_MACHINE}
      
      - name: Pull Docker image
        run: "docker pull kushal123123/backend-cloud-test:main &&
              docker run -d \
                -e MONOGO_URI=${MONOGO_URI} \
                -e JWT_SECRET=${JWT_SECRET} \
                -p 4000:4000 \
                kushal123123/backend-cloud-test:main"

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
